name: Stage publish

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - run: bun install --frozen-lockfile
      - run: npm stage publish --tag "latest"
